package com.github.eacryo.mongoflex.repository;

import com.github.eacryo.mongoflex.TestApplication;
import com.github.eacryo.mongoflex.bean.Character;
import com.github.eacryo.mongoflex.v2.CharacterRepository;
import com.github.eacryo.mongoflex.ulid.Ulid;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.Date;
import java.util.UUID;

@Slf4j
@SpringBootTest(classes = {TestApplication.class})
@ActiveProfiles("v2")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RepositoryDateIdTest {

    @Autowired
    private CharacterRepository repo;

    private String id;

    @Test
    @Order(1)
    void testCreateDateFilled() {
        log.info("=== test @CreateDate filled on insert ===");
        id = Ulid.generate();
        Character c = new Character();
        c.setId(id);
        c.setName("DateTset-" + id);
        c.setBirthday(new Date());
        Character inserted = repo.insert(c);
        log.info("inserted: createAt={}, updateAt={}", inserted.getCreateAt(), inserted.getUpdateAt());
        Assertions.assertNotNull(inserted.getCreateAt());
        // cleanup / 清理
        Character del = new Character();
        del.setId(id);
        del.setDeleted(true);
        repo.updateOneById(del);
    }

    @Test
    @Order(2)
    void testUpdateDateFilled() {
        log.info("=== test @UpdateDate filled on insert ===");
        id = Ulid.generate();
        Character c = new Character();
        c.setId(id);
        c.setName("DateTset-" + id);
        c.setBirthday(new Date());
        Character inserted = repo.insert(c);
        log.info("inserted: updateAt={}", inserted.getUpdateAt());
        Assertions.assertNotNull(inserted.getUpdateAt());
        // cleanup / 清理
        Character del = new Character();
        del.setId(id);
        del.setDeleted(true);
        repo.updateOneById(del);
    }

    @Test
    @Order(3)
    void testUpdateDateChangedOnUpdate() throws InterruptedException {
        log.info("=== test @UpdateDate changed on update ===");
        id = Ulid.generate();
        try {
            Character c = new Character();
            c.setId(id);
            c.setName("DateTset-" + id);
            c.setBirthday(new Date());
            Character inserted = repo.insert(c);
            Date originalCreateAt = inserted.getCreateAt();
            Date originalUpdateAt = inserted.getUpdateAt();
            log.info("after insert: createAt={}, updateAt={}", originalCreateAt, originalUpdateAt);

            Thread.sleep(1000);
            inserted.setAddress("Updated");
            repo.updateOneById(inserted);

            Character afterUpdate = repo.findById(id);
            log.info("after update: createAt={}, updateAt={}", afterUpdate.getCreateAt(), afterUpdate.getUpdateAt());
            Assertions.assertEquals(originalCreateAt, afterUpdate.getCreateAt());
            Assertions.assertNotEquals(originalUpdateAt, afterUpdate.getUpdateAt());
        } finally {
            Character del = new Character();
            del.setId(id);
            del.setDeleted(true);
            repo.updateOneById(del);
        }
    }

    @Test
    @Order(4)
    void testUlidAutoGenerated() {
        log.info("=== test ULID auto-generated ===");
        id = Ulid.generate();
        Character c = new Character();
        c.setId(id);
        c.setName("DateTset-" + id);
        c.setBirthday(new Date());
        Character inserted = repo.insert(c);
        log.info("id: {}", inserted.getId());
        Assertions.assertNotNull(inserted.getId());
        Assertions.assertEquals(26, inserted.getId().length());
        // cleanup / 清理
        Character del = new Character();
        del.setId(id);
        del.setDeleted(true);
        repo.updateOneById(del);
    }

    @Test
    @Order(5)
    void testIdAlreadySetNotOverwritten() {
        log.info("=== test id already set not overwritten ===");
        id = Ulid.generate();
        Character c = new Character();
        c.setId(id);
        c.setName("DateTset-" + id);
        c.setBirthday(new Date());
        Character inserted = repo.insert(c);
        Assertions.assertEquals(id, inserted.getId());
        log.info("id preserved: {}", id);
        // cleanup / 清理
        Character del = new Character();
        del.setId(id);
        del.setDeleted(true);
        repo.updateOneById(del);
    }

    @Test
    @Order(6)
    void testCreateDateNotOverwrittenOnUpdate() throws InterruptedException {
        log.info("=== test @CreateDate not overwritten on update ===");
        id = Ulid.generate();
        try {
            Character c = new Character();
            c.setId(id);
            c.setName("DateTset-" + id);
            c.setBirthday(new Date());
            Character inserted = repo.insert(c);
            Date originalCreateAt = inserted.getCreateAt();
            log.info("original createAt: {}", originalCreateAt);

            Thread.sleep(1000);
            inserted.setAddress("Changed");
            repo.updateOneById(inserted);

            Character afterUpdate = repo.findById(id);
            log.info("after update createAt: {}", afterUpdate.getCreateAt());
            Assertions.assertEquals(originalCreateAt, afterUpdate.getCreateAt());
        } finally {
            Character del = new Character();
            del.setId(id);
            del.setDeleted(true);
            repo.updateOneById(del);
        }
    }

}

